from decimal import Decimal
from typing import Any, NamedTuple, Protocol, Sequence, SupportsFloat

class FloatLike[T](SupportsFloat, Protocol):
    def __lt__(self, __other: T) -> bool: ...
    def __add__(self, __other: Any) -> T: ...
    def __sub__(self, __other: Any) -> T: ...
    def __mul__(self, __other: Any) -> T: ...
    def __truediv__(self, __other: Any) -> T: ...
    def __abs__(self) -> T: ...

class ValueRange(NamedTuple):
    min: Decimal
    max: Decimal

type Vec = Sequence[FloatLike]

def clamp(x, min_x, max_x): ...
def clamp_rgb(rgb): ...
def interp(piecewise: Sequence[Vec], x: float) -> Vec: ...
def nearest(stepwise: Sequence, x: float): ...
def make_decimal(x: FloatLike) -> Decimal: ...
def make_value_range(v: ValueRange | Sequence[FloatLike]) -> ValueRange: ...
def sfrexp10(value): ...

round_fractions: tuple[Decimal, ...]

def round_up_ish(value, round_fracs=...): ...
def roundness(value): ...
def most_round(values): ...
def pick_step_size(value_range, num_steps_hint, min_steps_per_label: int = 1) -> tuple[Decimal, Decimal]: ...
