from decimal import Decimal
from typing import Any, Callable, Iterable, NamedTuple, Protocol, Sequence, SupportsFloat

class FloatLike[T](SupportsFloat, Protocol):
    def __lt__(self, __other: Any) -> bool: ...
    def __le__(self, __other: Any) -> bool: ...
    def __add__(self, __other: Any) -> T: ...
    def __sub__(self, __other: Any) -> T: ...
    def __radd__(self, __other: Any) -> T: ...
    def __rsub__(self, __other: Any) -> T: ...
    def __mul__(self, __other: Any) -> T: ...
    def __rmul__(self, __other: Any) -> T: ...
    def __truediv__(self, __other: Any) -> T: ...
    def __abs__(self) -> T: ...

class ValueRange(NamedTuple):
    min: Decimal
    max: Decimal

def batched(iterable: Iterable, n: int): ...
def clamp(x, min_x, max_x): ...
def clamp_rgb(rgb): ...
def quantize(x: float, count: int): ...
def make_decimal(x: FloatLike) -> Decimal: ...
def sanitize_decimals(values: Sequence[Decimal]) -> Sequence[Decimal]: ...
def make_value_range(v: ValueRange | Sequence[FloatLike]) -> ValueRange: ...
def partial_first(f: Callable[[FloatLike, FloatLike], FloatLike]) -> Callable: ...
def partial_second(f: Callable[[FloatLike, FloatLike], FloatLike]) -> Callable: ...
def sfrexp10(value): ...

round_fractions: tuple[Decimal, ...]

def round_up_ish(value, round_fracs=...): ...
def roundness(value): ...
def roundness_ordered(values): ...
def most_round(values): ...
def first_non_none(values): ...
